OPENQASM 2.0;
include "qelib1.inc";

qreg node[4];
creg meas[4];
sx node[0];
sx node[1];
sx node[2];
sx node[3];
rz(0.5*pi) node[1];
sx node[1];
cx node[1],node[2];
cx node[1],node[0];
sx node[2];
rz(2.5*pi) node[2];
sx node[2];
rz(1.5*pi) node[2];
cx node[2],node[3];
sx node[3];
rz(2.5*pi) node[3];
sx node[3];
rz(1.5*pi) node[3];
cx node[3],node[2];
cx node[2],node[3];
cx node[3],node[2];
cx node[2],node[1];
cx node[1],node[2];
cx node[2],node[1];
cx node[1],node[0];
sx node[0];
rz(2.5*pi) node[0];
sx node[0];
rz(1.5*pi) node[0];
barrier node[2],node[3],node[1],node[0];
measure node[2] -> meas[0];
measure node[3] -> meas[1];
measure node[1] -> meas[2];
measure node[0] -> meas[3];
