name: CD
on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/cd.yml

permissions: {}

jobs:
  build-sdist:
    name: 🐍 Packaging
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-packaging-sdist.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    permissions:
      contents: read

  build-wheel:
    name: 🐍 Packaging
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-packaging-wheel-build.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    permissions:
      contents: read

  deploy:
    if: github.event_name == 'release' && github.event.action == 'published'
    name: 🚀 Deploy to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mqt.predictor
    needs: [build-sdist, build-wheel]
    permissions:
      attestations: write # Needed to attest the built artifacts
      contents: read
      id-token: write # Needed to attest and to publish to PyPI
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - name: Generate artifact attestation for sdist and wheel(s)
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-path: "dist/*"
      - uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
