name: Templating
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/templating.yml"
  workflow_dispatch: # Allow manual triggering

permissions: {}

jobs:
  render-template:
    name: Render template
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - id: create-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write # Needed to push the templating branch
          permission-pull-requests: write # Needed to open the templating pull request
      - uses: munich-quantum-toolkit/templates@26c7cb8534daf355596bf0a31379ba84d097c768 # v1.5.1
        with:
          token: ${{ steps.create-token.outputs.token }}
          name: Predictor
          organization: ${{ github.repository_owner }}
          project-type: pure-python
          repository: ${{ github.event.repository.name }}
